x-rr-base: &rr-base

services:
  api-rr:
    build: ./server
    container_name: rumihome-api-rr
    restart: unless-stopped
    environment:
      FIREBASE_PROJECT_ID: rumihome-448217
      DB_PATH: /data/rumihome.db
    volumes:
      - ./data:/data
    networks:
      - rumihome-rr

  app-rr:
    build:
      context: ./app
      args:
        VITE_ADMIN_PATH: /rr/admin
        VITE_GUEST_PATH: /rr/reserva
        VITE_FIREBASE_API_KEY: AIzaSyCpuL_aoKkogaWtkhPKsnWRw68FP5J5ecg
        VITE_FIREBASE_AUTH_DOMAIN: rumihome-448217.firebaseapp.com
        VITE_FIREBASE_PROJECT_ID: rumihome-448217
        VITE_APP_ID: 1:315822949726:web:7e0d2556d560e170917bcf
        VITE_BASE_PATH: /rr/
    container_name: rumihome-app-rr
    restart: unless-stopped
    depends_on:
      - api-rr
    networks:
      - rumihome-rr

networks:
  rumihome-rr:
    name: rumihome-rr